#Generé automatiquement via pyuic5, avec un code qui le lance à la fin
#SEULs CHANGEMENTs : taille de la fenetre + ajouts de cases (cf plus bas)

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 356)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(20)  #ajouts de colonnes
        self.tableWidget.setRowCount(30)     #ajouts de lignes
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 25))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuGrosse_bite = QtWidgets.QMenu(self.menuEdition)
        self.menuGrosse_bite.setObjectName("menuGrosse_bite")
        self.menuPetite_bite = QtWidgets.QMenu(self.menuEdition)
        self.menuPetite_bite.setObjectName("menuPetite_bite")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stremio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOuvrir.setIcon(icon)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionDarian = QtWidgets.QAction(MainWindow)
        self.actionDarian.setObjectName("actionDarian")
        self.actionAnas = QtWidgets.QAction(MainWindow)
        self.actionAnas.setObjectName("actionAnas")
        self.actionAtime = QtWidgets.QAction(MainWindow)
        self.actionAtime.setObjectName("actionAtime")
        self.menuGrosse_bite.addAction(self.actionDarian)
        self.menuPetite_bite.addAction(self.actionAnas)
        self.menuPetite_bite.addAction(self.actionAtime)
        self.menuEdition.addAction(self.menuGrosse_bite.menuAction())
        self.menuEdition.addAction(self.menuPetite_bite.menuAction())
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.toolBar.addAction(self.actionOuvrir)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nouvelle ligne"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nouvelle colonne"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nouvelle colonne"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuEdition.setTitle(_translate("MainWindow", "Bite"))
        self.menuGrosse_bite.setTitle(_translate("MainWindow", "Grosse bite"))
        self.menuPetite_bite.setTitle(_translate("MainWindow", "Petites bites"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionOuvrir.setToolTip(_translate("MainWindow", "infobulle"))
        self.actionDarian.setText(_translate("MainWindow", "Darian"))
        self.actionAnas.setText(_translate("MainWindow", "Anas"))
        self.actionAtime.setText(_translate("MainWindow", "Atime"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized() #Maximise la fenetre a l'ouverture
    sys.exit(app.exec_())

